import { allRecords, storeRecord, removeRecord } from './storage.js';
import { providerKinds, providerStatus } from './providers.js';
const main = document.querySelector('#main');
const tabs = [...document.querySelectorAll('.bottom button')];
let current = 'home';
const e = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',3600)}
function route(name){current=name;history.replaceState(null,'','#'+name);render();window.scrollTo(0,0)}
function button(label,where,secondary=false){return `<button class="${secondary?'secondary':'primary'}" data-go="${where}">${label}</button>`}
const tools=[['Create Story','📖','A place for your ideas','story'],['Character Generator','🧑‍🎨','Save a character reference','characters'],['Cartoon Image','🎨','Coming in stage 3','image'],['Song Generator','🎵','Coming in stage 5','song'],['Voice Generator','🎙','Coming in stage 5','voice'],['Music Generator','🎼','Coming in stage 5','music'],['Poster / Thumbnail','🖼','Coming in stage 7','poster'],['My Projects','📁','Your saved drafts','projects'],['Settings','⚙','Provider status and storage','settings']];
async function render(){tabs.forEach(tab=>{tab.classList.toggle('active',tab.dataset.route===current);tab.setAttribute('aria-current',tab.dataset.route===current?'page':'false')});
 try{
 if(current==='home'){main.innerHTML=`<section class="hero"><div class="eyebrow">Your cartoon studio</div><h1>Make a little world come alive.</h1><p>Start with an idea. Shape your characters and scenes, then build toward your cartoon video.</p>${button('✦ Create Cartoon Video','create')}</section><h2 class="section-title">What would you like to make?</h2><div class="grid">${tools.map(([name,icon,sub,to])=>`<button class="card tool" data-go="${to}"><span class="emoji">${icon}</span><b>${name}</b><small>${sub}</small></button>`).join('')}</div><div class="note">Stage 1 is ready: create and save ideas on this device. AI generation and video export are not connected yet.</div>`;return}
 if(current==='create'||current==='story'){main.innerHTML=`<div class="eyebrow">New project</div><h1 class="page">Start with your idea ✨</h1><p class="muted">A single line or a full script works. This stage saves your draft, but does not generate a story yet.</p><div class="steps"><span class="step current">1 Idea</span><span class="step">2 Story</span><span class="step">3 Characters</span><span class="step">4 Scenes</span><span class="step">5 Video</span></div><form id="projectForm" class="panel"><label class="field"><span>Project title</span><input name="title" maxlength="100" required placeholder="The moonlight adventure"></label><label class="field"><span>Your idea or script</span><textarea name="idea" required placeholder="Once upon a time..."></textarea></label><div class="row"><label class="field"><span>Age group</span><select name="age">${['General','0–2','2–4','4–6','6–10','10+'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="field"><span>Visual format</span><select name="dimension"><option>2D</option><option>3D</option></select></label></div><label class="field"><span>Style</span><select name="style"><option>Cute 2D</option><option>Storybook</option><option>Hand-Drawn</option></select></label><div class="row"><button type="submit" class="primary">Save project</button><button type="button" class="secondary" data-generate="text">Generate story</button></div></form><div class="note">AI provider not configured. Your saved idea stays on this phone, not in a shared cloud account.</div>`;return}
 if(current==='projects'){let items=(await allRecords('projects')).sort((a,b)=>b.updatedAt-a.updatedAt);main.innerHTML=`<div class="eyebrow">Your workspace</div><h1 class="page">My projects</h1><p class="muted">Saved in this browser on this device. Clearing site data or using a different browser removes access to these drafts.</p>${items.length?`<div class="panel">${items.map(item=>`<div class="item"><span class="emoji">🎬</span><div class="item-info"><b>${e(item.title)}</b><small>${e(item.dimension)} · ${e(item.age)} · ${new Date(item.updatedAt).toLocaleDateString()}</small></div><button class="secondary" data-open="${e(item.id)}">Open</button></div>`).join('')}</div>`:`<div class="panel empty"><span class="emoji">📁</span><h2>No projects yet</h2><p class="muted">Your first story idea starts here.</p>${button('Create a project','create')}</div>`}`;return}
 if(current.startsWith('project:')){let id=current.slice(8),item=(await allRecords('projects')).find(x=>x.id===id);if(!item){route('projects');return}main.innerHTML=`<button class="secondary" data-go="projects">← Projects</button><h1 class="page">${e(item.title)}</h1><span class="badge">Idea draft</span><div class="panel"><p><strong>Idea or script</strong></p><p style="white-space:pre-wrap;overflow-wrap:anywhere">${e(item.idea)}</p><p class="muted">${e(item.age)} · ${e(item.dimension)} · ${e(item.style)}</p><button class="secondary" data-edit="${e(id)}">Edit idea</button></div><div class="note">Story, scenes and video generation arrive in later stages. AI provider not configured.</div><button class="danger" data-delete="${e(id)}">Delete project</button>`;return}
 if(current==='characters'){let items=await allRecords('characters');main.innerHTML=`<div class="eyebrow">Character library</div><h1 class="page">Your characters</h1><p class="muted">Record consistent character descriptions to reuse in future scenes.</p><form id="characterForm" class="panel"><label class="field"><span>Name</span><input name="name" required maxlength="80" placeholder="Milo"></label><label class="field"><span>Type or species</span><input name="type" maxlength="100" placeholder="A curious fox"></label><label class="field"><span>Colors, clothes and personality</span><textarea name="description" placeholder="Orange fur, blue scarf, adventurous..."></textarea></label><button class="primary">Save character</button></form>${items.length?`<div class="panel">${items.map(item=>`<div class="item"><span class="emoji">☺</span><div class="item-info"><b>${e(item.name)}</b><small>${e(item.type)} · ${e(item.description)}</small></div><button class="danger" data-remove-character="${e(item.id)}">Delete</button></div>`).join('')}</div>`:''}`;return}
 if(current==='settings'){main.innerHTML=`<div class="eyebrow">Studio setup</div><h1 class="page">Settings</h1><div class="panel"><h2>AI providers</h2><p class="muted">No AI service is connected. Generation buttons will not produce pretend output.</p>${providerKinds.map(kind=>`<div class="item"><div class="item-info"><b>${e(kind[0].toUpperCase()+kind.slice(1))}</b><small>${providerStatus(kind)}</small></div></div>`).join('')}</div><div class="panel"><h2>On-device storage</h2><p class="muted">Projects, characters and backgrounds use IndexedDB in this browser. They are not synchronized across devices or installed and browser modes.</p><span class="badge" id="offlineStatus">Checking offline readiness…</span></div><div class="note">Stage 1 foundation. Story AI, visuals, animation, sound and final MP4 are planned stages, not available yet.</div>`;if(navigator.serviceWorker)navigator.serviceWorker.ready.then(()=>{let el=document.querySelector('#offlineStatus');if(el)el.textContent='Offline shell ready'});return}
 if(['image','song','voice','music','poster'].includes(current)){let name=tools.find(x=>x[3]===current)?.[0]||'Generator';main.innerHTML=`<button class="secondary" data-go="home">← Home</button><h1 class="page">${e(name)}</h1><div class="panel empty"><span class="emoji">✦</span><h2>Coming in a later stage</h2><p class="muted">AI provider not configured. No generation is available yet.</p></div>`;return}
 route('home')
 }catch(error){main.innerHTML=`<div class="panel"><h2>Could not open local storage</h2><p class="muted">${e(error.message)}. Check that your browser allows site storage, then reload.</p></div>`}}
document.addEventListener('click',async event=>{let t=event.target.closest('[data-route],[data-go],[data-generate],[data-open],[data-delete],[data-edit],[data-remove-character]');if(!t)return;if(t.dataset.route||t.dataset.go)route(t.dataset.route||t.dataset.go);else if(t.dataset.generate)toast('AI provider not configured');else if(t.dataset.open)route('project:'+t.dataset.open);else if(t.dataset.edit){let item=(await allRecords('projects')).find(x=>x.id===t.dataset.edit);if(item){route('create');let f=document.querySelector('#projectForm');f.dataset.edit=item.id;for(let key of ['title','idea','age','dimension','style'])if(f.elements[key])f.elements[key].value=item[key];f.elements.dimension.dispatchEvent(new Event('change'));f.elements.style.value=item.style}}else if(t.dataset.delete){if(confirm('Delete this project from this device?')){await removeRecord('projects',t.dataset.delete);route('projects');toast('Project deleted')}}else if(t.dataset.removeCharacter){if(confirm('Delete this character?')){await removeRecord('characters',t.dataset.removeCharacter);render()}}});
document.addEventListener('change',event=>{if(event.target.name==='dimension'){let styles=event.target.value==='3D'?['Cute 3D','Stylized 3D','Cinematic']:['Cute 2D','Storybook','Hand-Drawn'];event.target.form.elements.style.innerHTML=styles.map(x=>`<option>${x}</option>`).join('')}});
document.addEventListener('submit',async event=>{if(event.target.id==='projectForm'){event.preventDefault();let f=event.target,v=Object.fromEntries(new FormData(f));let now=Date.now();let id=f.dataset.edit||crypto.randomUUID();await storeRecord('projects',{id,...v,updatedAt:now});toast('Project saved on this device');route('project:'+id)}else if(event.target.id==='characterForm'){event.preventDefault();let v=Object.fromEntries(new FormData(event.target));await storeRecord('characters',{id:crypto.randomUUID(),...v,updatedAt:Date.now()});toast('Character saved');render()}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(error=>console.warn('Offline cache unavailable',error));
route(location.hash.slice(1)||'home');
