// Local-only storyboard export. Still frames, recorded/uploaded narration, no server or AI calls.
import {allRecords,storeRecord} from './storage.js';
import {generate} from './providers.js?v=6';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let micStream,voiceRecorder,voiceChunks=[];
const mime=()=>['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4','video/webm;codecs=vp8,opus','video/webm'].find(x=>MediaRecorder.isTypeSupported(x));
export async function showVideoStudio(main,id){
 const project=(await allRecords('projects')).find(x=>x.id===id);if(!project)return false;
 const images=project.images||[];const selected=(project.videoScenes||[]).filter(x=>images.some(i=>i.id===x.id));
 main.innerHTML=`<button class="secondary" data-go="project:${esc(id)}">← Project</button><div class="eyebrow">Scene video test</div><h1 class="page">${esc(project.title)} · Video</h1><p class="muted">Choose 2 or 3 saved stills, record or upload narration, then export a short video on this device. Stills do not animate. The file format depends on your browser.</p><div class="panel"><h2>1 · Choose scenes in order</h2>${images.length?images.map((im,i)=>`<label class="scene-pick"><input type="checkbox" value="${esc(im.id)}" ${selected.some(x=>x.id===im.id)?'checked':''}><img src="${URL.createObjectURL(im.blob)}" alt="${esc(im.prompt)}"><span><b>${esc(im.pipeline==='3d-style'?'3D-style':'2D')} frame ${i+1}</b><small>${esc(im.prompt)}</small></span></label>`).join(''):'<p class="muted">No saved images in this project. Make 2 or 3 images first.</p>'}<p class="muted">Each selected scene lasts 5 seconds. Tap in story order; the numbered order appears below.</p><ol id="sceneOrder">${selected.map(x=>`<li>${esc(images.find(i=>i.id===x.id)?.prompt||'Scene')}</li>`).join('')}</ol></div><div class="panel"><h2>2 · Narration</h2><label class="field"><span>AI narration text (English)</span><textarea id="narrationText" maxlength="1200" placeholder="Write 2 or 3 short sentences for the scenes">${esc(project.videoNarrationText||String(project.story?.narration||'').slice(0,1200))}</textarea></label><button type="button" class="primary" id="generateVoice">Generate AI narration (free allowance)</button><p class="muted">Preview the generated voice before export. Or use your own recording below.</p><div class="row"><button type="button" class="secondary" id="startVoice">Record narration</button><button type="button" class="secondary" id="stopVoice" disabled>Stop recording</button></div><label class="field"><span>Or choose a voice recording from this phone</span><input id="voiceFile" type="file" accept="audio/*"></label><p id="voiceStatus" class="key-status" role="status">${project.voice?.blob?'Narration saved on this device.':'No narration saved.'}</p>${project.voice?.blob?`<audio controls src="${URL.createObjectURL(project.voice.blob)}"></audio><button type="button" class="danger" id="removeVoice">Remove narration</button>`:''}</div><div class="panel"><h2>3 · Export</h2><p class="muted">This runs in real time. Keep this tab open and your phone awake until the download appears. No upload is needed. Your browser chooses MP4 if supported, otherwise WebM.</p><button id="exportVideo" class="primary" ${images.length<2?'disabled':''}>Export short video</button><p id="videoStatus" class="key-status" role="status">${selected.length} scenes selected. ${project.voice?.blob?'Narration ready.':'Add narration to include audio.'}</p><div id="videoResult"></div></div>`;
 const status=main.querySelector('#videoStatus');let order=selected.map(x=>x.id);
 main.querySelectorAll('.scene-pick input').forEach(input=>input.onchange=async()=>{
  if(input.checked){if(order.length>=3){input.checked=false;status.textContent='Choose at most 3 scenes.';return}order.push(input.value)}else order=order.filter(x=>x!==input.value);
  project.videoScenes=order.map(id=>({id}));await storeRecord('projects',project);
  main.querySelector('#sceneOrder').innerHTML=order.map(id=>`<li>${esc(images.find(x=>x.id===id)?.prompt||'Scene')}</li>`).join('');status.textContent=`${order.length} scenes selected in this order.`;
 });
 main.querySelector('#generateVoice').onclick=async event=>{let button=event.currentTarget,text=main.querySelector('#narrationText').value.trim(),voiceStatus=main.querySelector('#voiceStatus');if(!text){voiceStatus.textContent='Write narration text first.';return}button.disabled=true;voiceStatus.textContent='Generating AI narration with your free Worker…';try{const result=await generate('voice',{text});project.videoNarrationText=text;project.voice={blob:result.blob,createdAt:Date.now(),model:result.model};await storeRecord('projects',project);voiceStatus.textContent='AI narration saved. Reopen this video screen to preview it.';status.textContent='AI narration ready for export.'}catch(error){voiceStatus.textContent=`AI narration failed: ${error.message||'Unknown error'}. You can record or upload your voice instead.`}finally{button.disabled=false}};
 main.querySelector('#startVoice').onclick=async()=>{
  try{micStream=await navigator.mediaDevices.getUserMedia({audio:true});const type=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(x=>MediaRecorder.isTypeSupported(x));voiceRecorder=new MediaRecorder(micStream,type?{mimeType:type}:undefined);voiceChunks=[];voiceRecorder.ondataavailable=e=>{if(e.data.size)voiceChunks.push(e.data)};voiceRecorder.onstop=async()=>{micStream.getTracks().forEach(t=>t.stop());let blob=new Blob(voiceChunks,{type:voiceRecorder.mimeType});project.voice={blob,createdAt:Date.now()};await storeRecord('projects',project);main.querySelector('#voiceStatus').textContent='Narration saved. Reopen this video screen to play it.';status.textContent='Narration ready.'};voiceRecorder.start();main.querySelector('#startVoice').disabled=true;main.querySelector('#stopVoice').disabled=false;main.querySelector('#voiceStatus').textContent='Recording...';}
  catch(e){main.querySelector('#voiceStatus').textContent=`Microphone unavailable: ${e.message}`}
 };
 main.querySelector('#stopVoice').onclick=()=>{if(voiceRecorder?.state==='recording')voiceRecorder.stop();main.querySelector('#stopVoice').disabled=true;main.querySelector('#startVoice').disabled=false};
 main.querySelector('#voiceFile').onchange=async event=>{let file=event.target.files[0];if(!file)return;if(!file.type.startsWith('audio/')){main.querySelector('#voiceStatus').textContent='Choose an audio file.';return}project.voice={blob:file,createdAt:Date.now()};await storeRecord('projects',project);main.querySelector('#voiceStatus').textContent=`Narration saved: ${file.name}`;status.textContent='Narration ready.'};
 const remove=main.querySelector('#removeVoice');if(remove)remove.onclick=async()=>{delete project.voice;await storeRecord('projects',project);remove.remove();main.querySelector('audio')?.remove();main.querySelector('#voiceStatus').textContent='Narration removed.'};
 main.querySelector('#exportVideo').onclick=async event=>{const button=event.currentTarget;if(order.length<2||order.length>3){status.textContent='Choose 2 or 3 scenes first.';return}if(!project.voice?.blob){status.textContent='Record or upload narration before export.';return}button.disabled=true;try{await exportVideo(project,order,status,main.querySelector('#videoResult'))}catch(e){status.textContent=`Export failed: ${e.message}. Your scenes and narration remain saved.`}finally{button.disabled=false}};
 return true;
}
async function exportVideo(project,order,status,result){
 if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)throw Error('This browser cannot record a canvas video');
 const format=mime();if(!format)throw Error('This browser supports neither MP4 nor WebM recording');
 const scenes=order.map(id=>project.images.find(x=>x.id===id));if(scenes.some(x=>!x?.blob))throw Error('A selected image is missing');
 const loaded=[];for(const item of scenes){let url=URL.createObjectURL(item.blob),img=new Image();try{await new Promise((yes,no)=>{img.onload=yes;img.onerror=no;img.src=url})}finally{URL.revokeObjectURL(url)}loaded.push(img)}
 const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Canvas unavailable');
 const draw=index=>{ctx.fillStyle='#111218';ctx.fillRect(0,0,640,360);let im=loaded[index],scale=Math.min(640/im.width,360/im.height),w=im.width*scale,h=im.height*scale;ctx.drawImage(im,(640-w)/2,(360-h)/2,w,h)};draw(0);
 const audio=new (window.AudioContext||window.webkitAudioContext)();let stream,recorder,source;
 try{
  const buffer=await audio.decodeAudioData(await project.voice.blob.arrayBuffer());const destination=audio.createMediaStreamDestination();source=audio.createBufferSource();source.buffer=buffer;source.connect(destination);
  stream=canvas.captureStream(12);destination.stream.getAudioTracks().forEach(t=>stream.addTrack(t));recorder=new MediaRecorder(stream,{mimeType:format,videoBitsPerSecond:1500000});
  const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
  const done=new Promise((yes,no)=>{recorder.onerror=e=>no(e.error||Error('Recorder failed'));recorder.onstop=()=>yes()});
  recorder.start(1000);source.start();const started=performance.now(),length=order.length*5000;
  status.textContent=`Recording ${order.length} still scenes with narration. Keep this tab open…`;
  while(performance.now()-started<length){let elapsed=performance.now()-started,index=Math.min(order.length-1,Math.floor(elapsed/5000));draw(index);status.textContent=`Recording scene ${index+1}/${order.length}…`;await new Promise(r=>setTimeout(r,80))}
  if(recorder.state!=='inactive')recorder.stop();source.stop();await done;
  if(!chunks.length)throw Error('Recorder returned an empty file');
  const extension=recorder.mimeType.includes('mp4')?'mp4':'webm',blob=new Blob(chunks,{type:recorder.mimeType});if(blob.size<1000)throw Error('Video file is empty');
  const url=URL.createObjectURL(blob),name=`${String(project.title||'cartoon').replace(/[^a-z0-9]+/gi,'-').slice(0,45)}-test.${extension}`;
  result.innerHTML=`<video controls playsinline class="generated-image" src="${url}"></video><a class="primary" href="${url}" download="${name}" style="display:inline-block;margin-top:10px">Download ${extension.toUpperCase()} video</a>`;
  status.textContent=`Export ready: ${order.length} scenes, ${Math.round(blob.size/1024)} KB ${extension.toUpperCase()} with narration. Play it here, then download. Save it before leaving this screen.`;
 }finally{if(recorder?.state==='recording')recorder.stop();if(source)try{source.stop()}catch{}stream?.getTracks().forEach(t=>t.stop());await audio.close()}
}
